### Test app
GET http://localhost:3000

### Get all products
GET http://localhost:3000/products

### Add product
POST http://localhost:3000/products/add
Content-Type: application/json

{
  "name": "Backpack",
  "price": 300,
  "description": "Gamer Backpack"
}

### Delete product
DELETE http://localhost:3000/products/1

### Get all orders
GET http://localhost:3000/orders

### Add order
POST http://localhost:3000/orders/add
Content-Type: application/json

{
  "userId": 1,
  "productIds": [1,2],
  "totalAmount": 1000
}

### Delete order
DELETE http://localhost:3000/orders/1

### Register user
POST http://localhost:3000/users/register
Content-Type: application/json

{
  "username": "user2",
  "password": "pass2"
}

### Get last registered user
GET http://localhost:3000/users/me

### Delete user
DELETE http://localhost:3000/users/1